### ISSUE TITLE
Unique ID missing

### ISSUE THREAD

**Issue by derdanman** [cinzas/homeassistant-enigma-player#10]
Hi,
thanks for your work.

Seems like you missed asigning unique ID to the entities you create.

This prevents us from assigning areas or icons to these entities.

This might be a very small change with great benefits.

**Comment by steveuk23** [comment]
I'm also wanting this seen as the official integration isn't working that great.
Yours addon is working great @cinzas but it would be great to be able to add a unique_id
Thanks

**Comment by cinzas** [comment]
Hi @steveuk23 , @derdanman .

I will have a look on to it. Since it doesn't bother me, I never noticed.
May need to think of a away to get a uniqueid. The MAC is a good idea.

I also need to add a icon to the component.

**Comment by steveuk23** [comment]
> Hi @steveuk23 , @derdanman .
> 
> I will have a look on to it. Since it doesn't bother me, I never noticed. May need to think of a way to get a uniqueid. The MAC is a good idea.
> 
> I also need to add a icon to the component.

Thank you.
I wish I could help but it's a bit beyond me, I thought it was Home Assistant that dealt with the uniqueid I didn't realise the integration/add-on had to. 
Thanks again

**Comment by cinzas** [comment]
Hi

I have implemented the uniqueid.
V1.9 is released

![image](https://github.com/user-attachments/assets/e0577115-69a3-422c-8293-e9216964ff5a)


Also, many thanks to @hoffmann202 for his updates.
