### ISSUE TITLE
HomeKit bridge appliance of entity only shows 4 switches on Apple device

### ISSUE THREAD

**Issue by xyz667** [cinzas/homeassistant-enigma-player#12]
The component is working fine in HA for me, I can switch my Dreambox on and off and select channels.
When integrating this Dreambox entity in the Home app of Apple devices via the Home Assistant HomeKit bridge (as an accessory) only 4 switches (called "Switch" "Switch 2" ...) are shown, however. Three of those switches don't seem to do anything, with one switch I can switch the Dreambox on and off.
Other media player entities can be imported into Apple HomeKit just fine in that way?!

**Comment by cinzas** [comment]
Sorry i neved used HomeKit.

I will try to have a look in to it when I have some time.

**Comment by xyz667** [comment]
Hi @cinzas - I just found out that the solution is quite simple:
You just need to add `device_class: tv` and the device is correctly shown in HomeKit!

**Comment by xyz667** [comment]
Only one issue remains with regard to HomeKit: The `source_list` is mixed up in HomeKit. :-/

**Comment by cinzas** [comment]
@xyz667 , good to know, thanks

And you can customize it the way you want on HA :)
