### ISSUE TITLE
Off not recognized correctly

### ISSUE THREAD

**Issue by umtauscher** [cinzas/homeassistant-enigma-player#5]
This plugin only seems to work, if the box is switched on before starting HA.
If it's not, the integration doesn#t create the entity, which is then usesless, even after switching it on.

Am I doing something wrong or is this integration really only working with standby?

BTW when sitching the box off to deep standby the entity remains on status On.
Cheers

**Comment by cinzas** [comment]
Hi @umtauscher , sorry fot the delay on the replu.

I believe this is a issue I cannot solve. If the device is not connected at the boot time, it won't be recognized :(

I can have a look to see if I can improve something.

Thanks

**Comment by umtauscher** [comment]
Thanks, it really was some time ago.
Actually it seems to work now for several months
Cheers
