### ISSUE TITLE
Deprecation warning in HA 2024.1.5

### ISSUE THREAD

**Issue by majkers** [cinzas/homeassistant-enigma-player#7]
Hello I have this in my logs after upgrading to 2024.1.5

`2024-01-21 17:43:26.199 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.zgemma (<class 'custom_components.enigma.media_player.EnigmaMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|PLAY_MEDIA|VOLUME_STEP|SELECT_SOURCE|PLAY: 20413>, please create a bug report at https://github.com/cinzas/homeassistant-enigma-player/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Comment by cinzas** [comment]
Hi @majkers ,

Didn't notice that. Thanks for reporting. 2025 gives me a good time window :)
I will have a look as soon as I can, and fix it.

Thanks once again

**Comment by majkers** [comment]
No problem. Just a quick and shy remind of some ideas (like reload from UI) about new functionality from HS community forum :)

**Comment by cinzas** [comment]
Solved in v1.8 - https://github.com/cinzas/homeassistant-enigma-player/releases/tag/v1.8

**Comment by cinzas** [comment]
Closing
