### ISSUE TITLE
Cant power off Enigma 2

### ISSUE THREAD

**Issue by mercslkamg** [cinzas/homeassistant-enigma-player#9]
Message after update to Core 2024.2.3 supervisor 2024.02.0
Has no attribute set_powerstate

**Comment by cinzas** [comment]
Hi @mercslkamg .
Can you enable debug and share more info/logs ?

I am not having that issue

**Comment by mercslkamg** [comment]
Hi have you done more than this in your config ?
# Example configuration.yaml entry
media_player:
  - platform: enigma2
    host: 192.168.XX.XX
    username: XXXX
    password: XXXXXXXXXXX

**Comment by mercslkamg** [comment]
I also have several enigma receivers, but have not managed to maneuver more than one. Tried adding more in config but no success, only one works for me.
And I am a beginner, happy to learn.

**Comment by mercslkamg** [comment]
Sorry 
Got problems 
I needed to change enigma to enigma2 to get rid of faults

My config
——————————————
media_player:
enigma2: 
  devices:
    - host: 192.168.x.xxx
      port: 80
      name: xxxxxxxx
      timeout: 20
      username: root
      password: xxxxxxxxx
      picon: picon
    - host: 192.168.x.xx
      port: 80
      name: xxxxxxxxx
      username: root
      password: xxxxx
      timeout: 20
      picon: screenshot
——————————————-
Does not work getting faults

Happy for your help cinzas

**Comment by mercslkamg** [comment]
I have made mistakes I had not installed the repositorie from hacs .
Sorry I am a new user.
Now I understand that I  used the component of HA only.
I put my configuration in configuration.yaml

Your example configuration where should I enter it ?
Now I got your enigma in custom_components (not before)

Apologies for getting it wrong from the start.

**Comment by PixelShorts** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 25 February 2024 at 00:22:36 (15 occurrences)
Last logged: 08:55:44

[139672925776320] 'OpenWebIfDevice' object has no attribute 'set_powerstate'
[139672965140928] 'OpenWebIfDevice' object has no attribute 'set_powerstate'
[139670814674752] 'OpenWebIfDevice' object has no attribute 'set_powerstate'
[139672415953984] 'OpenWebIfDevice' object has no attribute 'set_powerstate'
[139670775203264] 'OpenWebIfDevice' object has no attribute 'set_powerstate'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/enigma2/media_player.py", line 156, in async_turn_off
    await self._device.set_powerstate(PowerState.STANDBY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenWebIfDevice' object has no attribute 'set_powerstate'

**Comment by cinzas** [comment]
> I have made mistakes I had not installed the repositorie from hacs . Sorry I am a new user. Now I understand that I used the component of HA only. I put my configuration in configuration.yaml
> 
> Your example configuration where should I enter it ? Now I got your enigma in custom_components (not before)
> 
> Apologies for getting it wrong from the start.

You need to set it up on the configuration.yaml file :)

**Comment by cinzas** [comment]
> Logger: homeassistant.components.websocket_api.http.connection Source: components/websocket_api/commands.py:240 Integration: Home Assistant WebSocket API (documentation, issues) First occurred: 25 February 2024 at 00:22:36 (15 occurrences) Last logged: 08:55:44
> 
> [139672925776320] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139672965140928] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139670814674752] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139672415953984] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139670775203264] 'OpenWebIfDevice' object has no attribute 'set_powerstate' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service response = await hass.services.async_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service return await target(service_call) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call single_response = await _handle_entity_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/enigma2/media_player.py", line 156, in async_turn_off await self._device.set_powerstate(PowerState.STANDBY) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'OpenWebIfDevice' object has no attribute 'set_powerstate'

Hi @mercslkamg ,

You are not using my custom component, you are using the enigma2 integration, native of Home Assistant.
You are using this integration -  https://www.home-assistant.io/integrations/enigma2/
Report this on the HA github

**Comment by PixelShorts** [comment]
> > Logger: homeassistant.components.websocket_api.http.connection Source: components/websocket_api/commands.py:240 Integration: Home Assistant WebSocket API (documentation, issues) First occurred: 25 February 2024 at 00:22:36 (15 occurrences) Last logged: 08:55:44
> > [139672925776320] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139672965140928] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139670814674752] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139672415953984] 'OpenWebIfDevice' object has no attribute 'set_powerstate' [139670775203264] 'OpenWebIfDevice' object has no attribute 'set_powerstate' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service response = await hass.services.async_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service return await target(service_call) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call single_response = await _handle_entity_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/enigma2/media_player.py", line 156, in async_turn_off await self._device.set_powerstate(PowerState.STANDBY) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'OpenWebIfDevice' object has no attribute 'set_powerstate'
> 
> Hi @PixelShorts ,
> 
> You are not using my custom component, you are using the enigma2 integration, native of Home Assistant. You are using this integration - https://www.home-assistant.io/integrations/enigma2/ Report this on the HA github

Ahhh my apologies. I thought this was for that integration.

**Comment by cinzas** [comment]
PRoblem solved by  @mercslkamg  :)
Thanks
